name: beats
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.5
  on_audio_query: ^2.1.0
  permission_handler: ^10.2.0
  just_audio: ^0.9.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Bold.ttf
  #       - asset: fonts/Roboto-Regular.ttf
